# server port is set to 8083
server:
  port: 8083

# The database connection properties are set to the environment variables.
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db-host}:${db-port}/${db-name}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO_DEV}
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect