server:
  port: ${PORT}

spring:
  security:
    oauth2:
      client:
        provider:
          nextjs:
            issuer-uri: ${ISSUER_URI}
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
        #            user-info-uri: ${USER_INFO_URI}

        registration:
          nextjs:
            provider: nextjs
            client-id: nextjs
            client-secret: nextjs123
            authorization-grant-type:
              - authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: ${REDIRECT_URI}
              - client_secret_post
              - client_secret_basic
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers
        - SaveSession
      routes:
        - id: security-route
          uri: ${SECURITY_URI}
          predicates:
            - Path=/identity/**
          filters:
            - TokenRelay=
            - RewritePath=/identity/(?<segment>.*),/$\{segment}

        - id: content-discovery-route
          uri: ${CONTENT_DISCOVERY_URI}
          predicates:
            - Path=/content/**
          filters:
            - TokenRelay=
            - RewritePath=/content/(?<segment>.*),/$\{segment}

        - id: asset-route
          uri: ${ASSET_URI}
          predicates:
            - Path=/asset/**
          filters:
            - TokenRelay=
            - RewritePath=/asset/(?<segment>.*),/$\{segment}

        - id: communication-route
          uri: ${COMMUNICATION_URI}
          predicates:
            - Path=/communication/**
          filters:
            - TokenRelay=
            - RewritePath=/communication/(?<segment>.*),/$\{segment}

        - id: order-route
          uri: ${ORDER_URI}
          predicates:
            - Path=/order/**
          filters:
            - TokenRelay=
            - RewritePath=/order/(?<segment>.*),/$\{segment}

        - id: event-ticket-route
          uri: ${EVENT_TICKET_URI}
          predicates:
            - Path=/event-ticket/**
          filters:
            - TokenRelay=
            - RewritePath=/event-ticket/(?<segment>.*),/$\{segment}

        - id: payment-route
          uri: ${PAYMENT_URI}
          predicates:
            - Path=/payment/**
          filters:
            - TokenRelay=
            - RewritePath=/payment/(?<segment>.*),/$\{segment}

        - id: user-profile-route
          uri: ${USER_PROFILE_URI}
          predicates:
            - Path=/user-profile/**
          filters:
            - TokenRelay=
            - RewritePath=/user-profile/(?<segment>.*),/$\{segment}

        - id: nextjs
          uri: ${NEXTJS_URI}
          predicates:
            - Path=/**


client-security-matchers: >
  /login/**,
  /logout/**,
  /organizer/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /profile/**,
  /asset/**,
  /communication/**,
  /order/**,
  /event-ticket/**,
  /payment/**,
  /user-profile/**,
  /content/**,
  /identity/**,
  /user-profile/**,

client-permit-matchers: >
  /login/**,
  /logout/**,
  /oauth2/**,
  /en/**,
  /auth/**,
  /contactSupport/**,
  /error/**,
  /actuator/**,
  /info/**,
  /health/**,
  /prometheus/**,
  /profile/**,
  /asset/**,
  /communication/**,
  /order/**,
  /event-ticket/**,
  /payment/**,
  /content/**,
  /identity/**,
  /user-profile/**

eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE}
server-logout-url: ${SERVER_LOGOUT_URL}