server:
  port: 8082
spring:
  data:
    mongodb:
      host: ${HOST}
      port: ${PORT}
      database: ${DB_NAME}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}
      authentication-database: ${AUTHENTICATION-DATABASE}

